### ISSUE TITLE
There's always one more <?PHP

### ISSUE THREAD

**Issue by linjialiang** [atom-ide-community/atom-ide-markdown-service#5]
> There's always one more `<?PHP`

![图片](https://user-images.githubusercontent.com/8848263/56399300-c0693600-627f-11e9-9a82-fdf55991153b.png)

**Comment by appelgriebsch** [comment]
Hey, as this is delivered by the lsp as part of the snippet for a data tip, I've made an improvement in the datatip component to deal with these kind of language preambles. Please check it out.

**Comment by linjialiang** [comment]
> All right, thank you
